openapi: 3.0.3
info:
  title: ClubManager API
  description: >
    Specification for the ClubManager API,
    used by web and mobile clients to interact with the server.
  version: 0.1.0
tags:
  - name: member
    description: Creating, updating, and getting members.
  - name: membership
    description: >
      Creating, updating, and getting memberships (which can contain multiple
      members), including registration.
  - name: bike
    description: >
      Creating, updating, and getting bikes as assigned to memberships.
  - name: event
    description: Creating, updating, and getting events.
  - name: eventType
    description: Creating, updating, and getting eventTypes.
  - name: job
    description: Creating, updating, and getting jobs.
  - name: jobType
    description: Creating, updating, and getting jobTypes.
  - name: workPoints
    description: Obtaining verified work points for a member or membership.
  - name: eventJob
    description: >
      Relating events and jobs: by default, *this* event type needs
      *X* amount of *that* job type.
  - name: billing
    description: >
      Handling billing calculation, distribution, payment, and retrieval.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    badRequestError:
      description: "Bad Request: Request body is missing or invalid"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
    unauthorizedError:
      description: "Unauthorized: ID token is missing or invalid"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
    forbiddenError:
      description: >
        Forbidden: The user has insufficient permissions for this resource
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
    notFoundError:
      description: "Not Found: The resource does not exist"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerError:
      description: >
        Internal Server Error: The server has had an error unrelated to the
        user's actions
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
  schemas:
    integer:
      type: integer
      format: int32
      minimum: 0
    number: # to handle floats
      type: number
      minimum: 0
    string:
      type: string
      maxLength: 255
    shortString:
      type: string
      maxLength: 50
    uuid:
      type: string
      format: uuid
    date:
      type: string
      format: date
    email:
      type: string
      format: email
      maxLength: 255
    errorResponse:
      type: object
      properties:
        reason:
          type: string
    member:
      type: object
      properties:
        member_id:
          $ref: "#/components/schemas/integer"
        membership_admin:
          $ref: "#/components/schemas/string"
        uuid:
          $ref: "#/components/schemas/uuid"
        member_type:
          $ref: "#/components/schemas/string"
        first_name:
          $ref: "#/components/schemas/string"
        last_name:
          $ref: "#/components/schemas/string"
        phone_number:
          type: string
        occupation:
          $ref: "#/components/schemas/string"
        email:
          $ref: "#/components/schemas/email"
        birthdate:
          $ref: "#/components/schemas/date"
        date_joined:
          $ref: "#/components/schemas/date"
        address:
          $ref: "#/components/schemas/string"
        city:
          $ref: "#/components/schemas/string"
        state:
          $ref: "#/components/schemas/string"
        zip:
          $ref: "#/components/schemas/string"
        last_modified_date:
          $ref: "#/components/schemas/date"
        last_modified_by:
          $ref: "#/components/schemas/string"
    membership:
      type: object
      properties:
        membership_id:
          $ref: "#/components/schemas/integer"
        membership_admin:
          $ref: "#/components/schemas/string"
        active:
          type: boolean
        cur_year_paid:
          type: boolean
        cur_year_renewed:
          type: boolean
        view_online:
          type: boolean
        renewal_sent:
          type: boolean
        year_joined:
          $ref: "#/components/schemas/integer"
        address:
          $ref: "#/components/schemas/string"
        city:
          $ref: "#/components/schemas/string"
        state:
          $ref: "#/components/schemas/string"
        zip:
          $ref: "#/components/schemas/string"
        last_modified_date:
          $ref: "#/components/schemas/date"
        last_modified_by:
          $ref: "#/components/schemas/string"
    registration:
      type: object
      properties:
        member_type:
          $ref: "#/components/schemas/string"
        first_name:
          $ref: "#/components/schemas/string"
        last_name:
          $ref: "#/components/schemas/string"
        phone_number:
          type: string
        occupation:
          $ref: "#/components/schemas/string"
        email:
          $ref: "#/components/schemas/email"
        birthdate:
          $ref: "#/components/schemas/date"
        address:
          $ref: "#/components/schemas/string"
        city:
          $ref: "#/components/schemas/string"
        state:
          $ref: "#/components/schemas/string"
        zip:
          $ref: "#/components/schemas/string"
    bike:
      type: object
      properties:
        bike_id:
          $ref: "#/components/schemas/integer"
        year:
          $ref: "#/components/schemas/shortString"
        make:
          $ref: "#/components/schemas/shortString"
        model:
          $ref: "#/components/schemas/shortString"
        membership_admin:
          $ref: "#/components/schemas/string"
    event:
      type: object
      properties:
        event_id:
          $ref: "#/components/schemas/integer"
        date:
          $ref: "#/components/schemas/date"
        event_type:
          $ref: "#/components/schemas/string"
        event_name:
          $ref: "#/components/schemas/string"
        event_description:
          $ref: "#/components/schemas/string"
    eventType:
      type: object
      properties:
        event_type_id:
          $ref: "#/components/schemas/integer"
        type:
          $ref: "#/components/schemas/string"
        last_modified_date:
          $ref: "#/components/schemas/date"
        last_modified_by:
          $ref: "#/components/schemas/string"
    job:
      type: object
      properties:
        job_id:
          $ref: "#/components/schemas/integer"
        member:
          $ref: "#/components/schemas/string"
        event:
          $ref: "#/components/schemas/string"
        event_date:
          $ref: "#/components/schemas/date"
        job_type:
          $ref: "#/components/schemas/string"
        verified:
          type: boolean
        verified_date:
          $ref: "#/components/schemas/date"
        points_awarded:
          $ref: "#/components/schemas/number"
        paid:
          type: boolean
        paid_date:
          $ref: "#/components/schemas/date"
        last_modified_date:
          $ref: "#/components/schemas/date"
        last_modified_by:
          $ref: "#/components/schemas/string"
    jobType:
      type: object
      properties:
        job_type_id:
          $ref: "#/components/schemas/integer"
        title:
          $ref: "#/components/schemas/string"
        point_value:
          $ref: "#/components/schemas/number"
        cash_value:
          $ref: "#/components/schemas/number"
        job_day:
          $ref: "#/components/schemas/string"
        reserved:
          type: boolean
        online:
          type: boolean
        meal_ticket:
          type: boolean
        sort_order:
          $ref: "#/components/schemas/integer"
        last_modified_date:
          $ref: "#/components/schemas/date"
        last_modified_by:
          $ref: "#/components/schemas/string"
    eventJob:
      type: object
      properties:
        event_job_id:
          $ref: "#/components/schemas/integer"
        event_type:
          $ref: "#/components/schemas/string"
        job_type:
          $ref: "#/components/schemas/string"
        count:
          $ref: "#/components/schemas/integer"
    bill:
      type: object
      properties:
        bill_id:
          $ref: "#/components/schemas/integer"
        generated_date:
          $ref: "#/components/schemas/date"
        year:
          $ref: "#/components/schemas/integer"
        amount:
          $ref: "#/components/schemas/number"
        amount_with_fee:
          $ref: "#/components/schemas/number"
        membership_admin:
          $ref: "#/components/schemas/string"
        membership_admin_email:
          $ref: "#/components/schemas/email"
        emailed_bill:
          $ref: "#/components/schemas/date"
        bill_status:
          $ref: "#/components/schemas/shortString"
security:
  - BearerAuth: [] 
paths:
  # member
  /api/member/new:
    post:
      tags:
        - member
      summary: Create a new member
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - member_type_id
                - modified_by
              additionalProperties: false
              properties:
                membership_id:
                  $ref: "#/components/schemas/integer"
                uuid:
                  $ref: "#/components/schemas/uuid"
                member_type_id:
                  $ref: "#/components/schemas/integer"
                first_name:
                  $ref: "#/components/schemas/string"
                last_name:
                  $ref: "#/components/schemas/string"
                phone_number:
                  type: string
                occupation:
                  $ref: "#/components/schemas/string"
                email:
                  $ref: "#/components/schemas/email"
                birthdate:
                  $ref: "#/components/schemas/date"
                date_joined:
                  $ref: "#/components/schemas/date"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/member"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/member/{memberID}:
    parameters:
      - name: memberID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - member
      summary: Get this member
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/member"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - member
      summary: Update this member
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - modified_by
              minProperties: 2
              additionalProperties: false
              properties:
                membership_id:
                  $ref: "#/components/schemas/integer"
                uuid:
                  $ref: "#/components/schemas/uuid"
                member_type_id:
                  $ref: "#/components/schemas/integer"
                first_name:
                  $ref: "#/components/schemas/string"
                last_name:
                  $ref: "#/components/schemas/string"
                phone_number:
                  type: string
                occupation:
                  $ref: "#/components/schemas/string"
                email:
                  $ref: "#/components/schemas/email"
                birthdate:
                  $ref: "#/components/schemas/date"
                date_joined:
                  $ref: "#/components/schemas/date"
                modified_by:
                  $ref: "#/components/schemas/integer"
            example:
              email: newemail@gmail.com
              phone_number: 585-123-4567
              modified_by: 42
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/member"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    delete:
      tags:
        - member
      summary: Delete this member
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  member_id:
                    $ref: "#/components/schemas/integer"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/member/list:
    get:
      tags:
        - member
      summary: Get all members
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: role
          in: query
          description: "Optional: filter members by a specific role"
          schema:
            type: string
            enum:
              - boardMember
              - member
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/member"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"

  # membership
  /api/membership/new:
    post:
      tags:
        - membership
      summary: Create a new membership
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - modified_by
              properties:
                year_joined:
                  $ref: "#/components/schemas/integer"
                address:
                  $ref: "#/components/schemas/string"
                city:
                  $ref: "#/components/schemas/string"
                state:
                  $ref: "#/components/schemas/string"
                zip:
                  $ref: "#/components/schemas/string"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/membership"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/membership/{membershipID}:
    parameters:
      - name: membershipID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - membership
      summary: Get this membership
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/membership"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - membership
      summary: Update this membership
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        **Note:** This endpoint is used to mark a membership as inactive, rather
        than using a `DELETE` endpoint to remove it entirely.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - modified_by
              minProperties: 2
              additionalProperties: false
              properties:
                active:
                  type: boolean
                cur_year_paid:
                  type: boolean
                cur_year_renewed:
                  type: boolean
                view_online:
                  type: boolean
                renewal_sent:
                  type: boolean
                year_joined:
                  $ref: "#/components/schemas/integer"
                address:
                  $ref: "#/components/schemas/string"
                city:
                  $ref: "#/components/schemas/string"
                state:
                  $ref: "#/components/schemas/string"
                zip:
                  $ref: "#/components/schemas/string"
                modified_by:
                  $ref: "#/components/schemas/integer"
            example:
              address: 1234 New Address Street
              city: Hoboken
              state: NJ
              zip: 07030
              modified_by: 42
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/membership"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/membership/list:
    get:
      tags:
        - membership
      summary: Get all memberships
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: status
          in: query
          description: "Optional: filter memberships by a specific status"
          schema:
            type: string
            enum: 
              - active
              - inactive
              - pending
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/membership"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/membership/register:
    post:
      tags:
        - membership
      summary: Register for a new membership
      security: []
      description: This request does not require authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - member_type_id
              properties:
                member_type_id:
                  $ref: "#/components/schemas/integer"
                first_name:
                  $ref: "#/components/schemas/string"
                last_name:
                  $ref: "#/components/schemas/string"
                phone_number:
                  type: string
                occupation:
                  $ref: "#/components/schemas/string"
                email:
                  $ref: "#/components/schemas/email"
                birthdate:
                  $ref: "#/components/schemas/date"
                address:
                  $ref: "#/components/schemas/string"
                city:
                  $ref: "#/components/schemas/string"
                state:
                  $ref: "#/components/schemas/string"
                zip:
                  $ref: "#/components/schemas/string"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/registration"
        400:
          $ref: "#/components/responses/badRequestError"
        500:
          $ref: "#/components/responses/internalServerError"
        
  # bike
  /api/bike/new:
    post:
      tags:
        - bike
      summary: Create a new bike
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - membership_id
              properties:
                year:
                  $ref: "#/components/schemas/shortString"
                make:
                  $ref: "#/components/schemas/shortString"
                model:
                  $ref: "#/components/schemas/shortString"
                membership_id:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bike"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/bike/{bikeID}:
    parameters:
      - name: bikeID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - bike
      summary: Get this bike
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bike"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - bike
      summary: Update this bike
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
              additionalProperties: false
              properties:
                year:
                  $ref: "#/components/schemas/shortString"
                make:
                  $ref: "#/components/schemas/shortString"
                model:
                  $ref: "#/components/schemas/shortString"
                membership_id:
                  $ref: "#/components/schemas/integer"
            example:
              membership_id: 101
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bike"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    delete:
      tags:
        - bike
      summary: Delete this bike
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  bike_id:
                    $ref: "#/components/schemas/integer"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/bike/list:
    get:
      tags:
        - bike
      summary: Get all bikes
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: membershipID
          in: query
          description: "Optional: pull bikes for a specific membership"
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/bike"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"

  # event
  /api/event/new:
    post:
      tags:
        - event
      summary: Create a new event
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  $ref: "#/components/schemas/date"
                event_type_id:
                  $ref: "#/components/schemas/integer"
                event_name:
                  $ref: "#/components/schemas/string"
                event_description:
                  $ref: "#/components/schemas/string"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/event/{eventID}:
    parameters:
      - name: eventID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - event
      summary: Get this event
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - event
      summary: Update this event
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
              additionalProperties: false
              properties:
                date:
                  $ref: "#/components/schemas/date"
                event_type_id:
                  $ref: "#/components/schemas/integer"
                event_name:
                  $ref: "#/components/schemas/string"
                event_description:
                  $ref: "#/components/schemas/string"
            example:
              date: 12/18/21
              event_name: Squeaky Training Wheels Invitational (Rescheduled)
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    delete:
      tags:
        - event
      summary: Delete this event
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_id:
                    $ref: "#/components/schemas/integer"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/event/list:
    get:
      tags:
        - event
      summary: Get all events
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: Range
          in: header
          description: |
            Optional: filter events by a specific timeframe.
            Format is one of:
            - `YYYYMMDD-YYYYMMDD`
            - `YYYYMMDD-`
            - `-YYYYMMDD`
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/event"
        206:
          description: Partial Content
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/event"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"
  
  # eventType
  /api/eventType/new:
    post:
      tags:
        - eventType
      summary: Create a new event type
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - modified_by
              properties:
                type:
                  $ref: "#/components/schemas/string"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eventType"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/eventType/{eventTypeID}:
    parameters:
      - name: eventTypeID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - eventType
      summary: Get this event type
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eventType"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - eventType
      summary: Update this event type
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        **Note:** This endpoint is used to mark an event type as inactive, rather
        than using a `DELETE` endpoint to remove it entirely.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - modified_by
              properties:
                type:
                  $ref: "#/components/schemas/string"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eventType"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/eventType/list:
    get:
      tags:
        - eventType
      summary: Get all event types
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eventType"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"

  # job
  /api/job/new:
    post:
      tags:
        - job
      summary: Create a new job
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_type_id
                - modified_by
              properties:
                member_id:
                  $ref: "#/components/schemas/integer"
                event_id:
                  $ref: "#/components/schemas/integer"
                job_type_id:
                  $ref: "#/components/schemas/integer"
                points_awarded:
                  $ref: "#/components/schemas/number"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/job/{jobID}:
    parameters:
      - name: jobID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - job
      summary: Get this job
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - job
      summary: Update this job
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        **Note 1:** This endpoint is used to verify work points.
        <br><br>
        **Note 2:** While most fields require admin permissions
        to update, both *1)* assigning the job to a member or paid laborer and
        *2)* checking in to the job can be done by a member as well.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - modified_by
              minProperties: 2
              additionalProperties: false
              properties:
                member_id:
                  $ref: "#/components/schemas/integer"
                event_id:
                  $ref: "#/components/schemas/integer"
                job_type_id:
                  $ref: "#/components/schemas/integer"
                verified:
                  type: boolean
                paid:
                  type: boolean
            example:
              verified: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    post:
      tags:
        - job
      summary: Clone this job
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    delete:
      tags:
        - job
      summary: Delete this job
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    $ref: "#/components/schemas/integer"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/job/list:
    get:
      tags:
        - job
      summary: Get all jobs
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: assignmentStatus
          in: query
          description: "Optional: filter jobs by a specific assignment status"
          schema:
            type: string
            enum:
              - open
              - assigned
        - name: verificationStatus
          in: query
          description: "Optional: filter jobs by a specific verification status"
          schema:
            type: string
            enum:
              - pending
              - verified
        - name: memberID
          in: query
          description: "Optional: pull jobs for a specific **member**"
          schema:
            type: integer
        - name: membershipID
          in: query
          description: "Optional: pull jobs for a specific **membership**"
          schema:
            type: integer
        - name: eventID
          in: query
          description: "Optional: pull jobs for a specific **event**"
          schema:
            type: integer
        - name: Range
          in: header
          description: |
            Optional: filter jobs by a specific timeframe.
            Format is one of:
            - `YYYYMMDD-YYYYMMDD`
            - `YYYYMMDD-`
            - `-YYYYMMDD`
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/job"
        206:
          description: Partial Content
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/job"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"
  
  # jobType
  /api/jobType/new:
    post:
      tags:
        - jobType
      summary: Create a new job type
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - reserved
                - online
                - meal_ticket
                - modified_by
              properties:
                title:
                  $ref: "#/components/schemas/string"
                point_value:
                  $ref: "#/components/schemas/number"
                cash_value:
                  $ref: "#/components/schemas/number"
                job_day:
                  $ref: "#/components/schemas/string"
                reserved:
                  type: boolean
                online:
                  type: boolean
                meal_ticket:
                  type: boolean
                sort_order:
                  $ref: "#/components/schemas/integer"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobType"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/jobType/{jobTypeID}:
    parameters:
      - name: jobTypeID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - jobType
      summary: Get this job type
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobType"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - jobType
      summary: Update this job type
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        **Note:** This endpoint is used to mark a job type as inactive, rather
        than using a `DELETE` endpoint to remove it entirely.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - modified_by
              minProperties: 2
              additionalProperties: false
              properties:
                title:
                  $ref: "#/components/schemas/string"
                point_value:
                  $ref: "#/components/schemas/number"
                cash_value:
                  $ref: "#/components/schemas/number"
                job_day:
                  $ref: "#/components/schemas/string"
                reserved:
                  type: boolean
                online:
                  type: boolean
                meal_ticket:
                  type: boolean
                sort_order:
                  $ref: "#/components/schemas/integer"
                modified_by:
                  $ref: "#/components/schemas/integer"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobType"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/jobType/list:
    get:
      tags:
        - jobType
      summary: Get all job types
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/jobType"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"
  
  # workPoints
  /api/workPoints/byMember/{memberID}:
    parameters:
      - name: memberID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - workPoints
      summary: Get the total verified work points for this member
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: year
          in: query
          description: "Optional: pull the work point total for a specific year"
          schema:
            type: integer
            default: the current year
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    $ref: "#/components/schemas/number"
        401:
          $ref: "#/components/responses/unauthorizedError"
        400:
          $ref: "#/components/responses/badRequestError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/workPoints/byMembership/{membershipID}:
    parameters:
      - name: membershipID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - workPoints
      summary: Get the total verified work points for this membership
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: year
          in: query
          description: "Optional: pull the work point total for a specific year"
          schema:
            type: integer
            default: the current year
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    $ref: "#/components/schemas/number"
        401:
          $ref: "#/components/responses/unauthorizedError"
        400:
          $ref: "#/components/responses/badRequestError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
  
  # eventJob
  /api/eventJob/new:
    post:
      tags:
        - eventJob
      summary: Create a new event-job instance
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - event_type_id
                - job_type_id
                - count
              properties:
                event_type_id:
                  $ref: "#/components/schemas/integer"
                job_type_id:
                  $ref: "#/components/schemas/integer"
                count:
                  $ref: "#/components/schemas/integer"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eventJob"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/eventJob/{eventJobID}:
    parameters:
      - name: eventJobID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - eventJob
      summary: Get this event-job instance
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eventJob"
        401:
          $ref: "#/components/responses/unauthorizedError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    patch:
      tags:
        - eventJob
      summary: Update this event-job instance
      description: >
        The request body needs only contain the fields with data to be updated.
        If data in a field should not be updated, that field can be omitted from
        the request body.
        <br><br>
        This endpoint requires an `Authorization: Bearer` header with a JWT ID token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
              additionalProperties: false
              properties:
                event_type_id:
                  $ref: "#/components/schemas/integer"
                job_type_id:
                  $ref: "#/components/schemas/integer"
                count:
                  $ref: "#/components/schemas/integer"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eventJob"
        400:
          $ref: "#/components/responses/badRequestError"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    delete:
      tags:
        - eventJob
      summary: Delete this event-job instance
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_job_id:
                    $ref: "#/components/schemas/integer"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"

  # billing
  /api/billing/yearlyWorkPointThreshold:
    get:
      tags:
        - billing
      summary: Get a year's work point threshold for completely subsidizing dues
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: year
          in: query
          description: "Optional: pull the threshold for a specific year"
          schema:
            type: integer
            default: the current year
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  year:
                    $ref: "#/components/schemas/integer"
                  threshold:
                    $ref: "#/components/schemas/integer"
        401:
          $ref: "#/components/responses/unauthorizedError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/billing/list:
    get:
      tags:
        - billing
      summary: Get all bills by payment status or year
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: paymentStatus
          in: query
          description: "Optional: filter bills by a specific payment status"
          schema:
            type: string
            enum:
              - paid
              - outstanding
        - name: year
          in: query
          description: "Optional: filter bills by a specific year"
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/bill"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/billing:
    post:
      tags:
        - billing
      summary: Calculate and distribute all bills for the year
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/bill"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        500:
          $ref: "#/components/responses/internalServerError"
  /api/billing/{membershipID}:
    parameters:
      - name: membershipID
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - billing
      summary: Get bills for this membership
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      parameters:
        - name: year
          in: query
          description: "Optional: filter bills by a specific year"
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/bill"
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"
    post:
      tags:
        - billing
      summary: Pay this membership's outstanding balance
      description: "This endpoint requires an `Authorization: Bearer` header with a JWT ID token."
      responses:
        200:
          description: OK
        401:
          $ref: "#/components/responses/unauthorizedError"
        403:
          $ref: "#/components/responses/forbiddenError"
        404:
          $ref: "#/components/responses/notFoundError"
        500:
          $ref: "#/components/responses/internalServerError"